"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import useSearchStore from "@/store/useSearchStore";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children, modal }) {
//   return (
//     <>
//       <html lang="en">
//         <body className={inter.className}>
//           <div className="flex flex-col h-screen">{children}</div>
//           {modal}
//           <div id="modal-root-id" />
//           <ToastContainer />
//         </body>
//       </html>
//     </>
//   );
// }

const RootLayout = ({ children, modal }) => {
  const { data, fetchData } = useSearchStore((state) => ({
    data: state.data,
    fetchData: state.fetchData,
  }));
  useEffect(() => {
    fetchData();
  }, []);
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <div className="flex flex-col h-screen">{children}</div>
          {modal}
          <div id="modal-root-id" />
          <ToastContainer />
        </body>
      </html>
    </>
  );
};

export default RootLayout;
